# Generated by Django 3.1.5 on 2021-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
